name: 编译巴法云stdoutsubc
on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:
  build:
    name: Build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: aarch64-linux-musl
          URL: aarch64-linux-musl
          
        - target: x86_64-linux-musl
          URL: x86_64-linux-musl
            
        - target: i686-linux-musl
          URL: i686-linux-musl
        
        - target: armv7-linux-musleabihf
          URL: armv7l-linux-musleabihf

        - target: armv7-linux-musleabi
          URL: armv7m-linux-musleabi
          
        - target: arm-linux-musleabihf
          URL: arm-linux-musleabihf

        - target: arm-linux-musleabi
          URL: arm-linux-musleabi

        - target: mipsel-linux-musl
          URL: mipsel-linux-muslsf

        - target: mips-linux-musl
          URL: mips-linux-muslsf

    runs-on: ubuntu-latest
    steps:
    
     - name: Checkout code
       uses: actions/checkout@v4
       with:
         repository: eclipse-paho/paho.mqtt.cpp
         ref: v1.5.1
       
     - name: 下载gcc
       uses: lmq8267/dl-musl@main
       with:
        target: ${{ matrix.URL }}
        static: true
        gccpath: /tmp
        
     - name: 安装 UPX
       uses: crazy-max/ghaction-upx@v3
       with:
        version: latest
        install-only: true
        
     - name: 编译
       run: |
         git submodule init
         git submodule update
         sudo apt install build-essential
         mkdir -p build && cd build
         export CC="$CC -static"
         export CXX="$CXX -static"
         cmake -DPAHO_BUILD_STATIC=ON -DPAHO_BUILD_SHARED=false -DPAHO_BUILD_EXAMPLES=true -DPAHO_WITH_SSL=false -DPAHO_HIGH_PERFORMANCE=TRUE -DPAHO_ENABLE_TESTING=false -DPAHO_WITH_MQTT_C=ON ..
         make
         cpack --verbose
         file _CPack_Packages/Linux/TGZ/PahoMqttCpp-1.5.1-Linux/bin/mqttpp_chat
         $STRIP _CPack_Packages/Linux/TGZ/PahoMqttCpp-1.5.1-Linux/bin/*
         file _CPack_Packages/Linux/TGZ/PahoMqttCpp-1.5.1-Linux/bin/mqttpp_chat
         upx --lzma --best _CPack_Packages/Linux/TGZ/PahoMqttCpp-1.5.1-Linux/bin/*
         
     - uses: actions/upload-artifact@v4
       with:
        name: stdoutsubc-${{ matrix.target }}
        path: build/_CPack_Packages/Linux/TGZ/PahoMqttCpp-1.5.1-Linux/bin/
